import { DEFAULT_LAYOUT } from '../base';
import { AppRouteRecordRaw } from '../types';

const DASHBOARD: AppRouteRecordRaw = {
  path: '/dashboard',
  name: 'dashboard',
  component: DEFAULT_LAYOUT,
  meta: {
    locale: 'menu.dashboard',
    requiresAuth: true,
    icon: 'icon-dashboard',
    order: 0,
  },
  children: [
    {
      path: 'workplace',
      name: 'Workplace',
      component: () => import('@/views/dashboard/workplace/index.vue'),
      meta: {
        locale: 'menu.dashboard.workplace',
        requiresAuth: true,
        roles: ['*'],
      },
    },
    {
      path: 'monitor',
      name: 'Monitor',
      component: () => import('@/views/dashboard/monitor/index.vue'),
      meta: {
        locale: 'menu.dashboard.monitor',
        requiresAuth: true,
        roles: ['admin'],
      },
    },
  ],
};

// MDM 业务路由
const MDM_ROUTES: AppRouteRecordRaw[] = [
  {
    path: '/members',
    name: 'Members',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.members',
      requiresAuth: true,
      icon: 'icon-user',
      order: 1,
    },
    children: [
      { path: '', redirect: '/members/list', meta: { hideInMenu: true }},
      {
        path: 'list',
        name: 'MemberList',
        component: () => import('@/views/members/MemberListView.vue'),
        meta: { locale: 'menu.members.list', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'points',
        name: 'MemberPoints',
        component: () => import('@/views/PointsRulesView.vue'),
        meta: { locale: 'menu.members.points', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'coupons',
        name: 'MemberCoupons',
        component: () => import('@/views/CouponsView.vue'),
        meta: { locale: 'menu.members.coupons', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'tags',
        name: 'MemberTags',
        component: () => import('@/views/MemberTags.vue'),
        meta: { locale: 'menu.members.tags', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'campaigns',
        name: 'Campaigns',
        component: () => import('@/views/Campaigns.vue'),
        meta: { locale: 'menu.members.campaigns', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'recharge',
        name: 'MemberRecharge',
        component: () => import('@/views/MemberRecharge.vue'),
        meta: { locale: 'menu.members.recharge', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'levels',
        name: 'MemberLevels',
        component: () => import('@/views/MemberLevels.vue'),
        meta: { locale: 'menu.members.levels', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'growth',
        name: 'MemberGrowth',
        component: () => import('@/views/MemberGrowth.vue'),
        meta: { locale: 'menu.members.growth', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'loyalty',
        name: 'LoyaltyProgram',
        component: () => import('@/views/LoyaltyProgram.vue'),
        meta: { locale: 'menu.members.loyalty', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'coupon-center',
        name: 'CouponCenter',
        component: () => import('@/views/CouponCenter.vue'),
        meta: { locale: 'menu.members.coupon', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/devices',
    name: 'Devices',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.devices',
      requiresAuth: true,
      icon: 'icon-device',
      order: 1,
    },
    children: [
      { path: '', redirect: '/devices/list', meta: { hideInMenu: true }},
      {
        path: 'list',
        name: 'DeviceList',
        component: () => import('@/views/DeviceList.vue'),
        meta: { locale: 'menu.devices.list', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'detail/:id',
        name: 'DeviceDetail',
        component: () => import('@/views/DeviceDetail.vue'),
        meta: { locale: 'menu.devices.detail', requiresAuth: true, roles: ['*'], hideInMenu: true },
      },
      {
        path: 'pairing',
        name: 'DevicePairing',
        component: () => import('@/views/DevicePairing.vue'),
        meta: { locale: 'menu.devices.pairing', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'groups',
        name: 'DeviceGroups',
        component: () => import('@/views/DeviceGroupsView.vue'),
        meta: { locale: 'menu.devices.groups', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'commands',
        name: 'DeviceCommands',
        component: () => import('@/views/DeviceCommands.vue'),
        meta: { locale: 'menu.devices.commands', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'geofence',
        name: 'GeofenceConfig',
        component: () => import('@/views/GeofenceConfig.vue'),
        meta: { locale: 'menu.devices.geofence', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'geofencing',
        name: 'Geofencing',
        component: () => import('@/views/Geofencing.vue'),
        meta: { locale: 'menu.devices.geofencing', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'registration',
        name: 'DeviceRegistration',
        component: () => import('@/views/DeviceRegistration.vue'),
        meta: { locale: 'menu.devices.registration', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'diagnostics',
        name: 'DeviceDiagnostics',
        component: () => import('@/views/DeviceDiagnostics.vue'),
        meta: { locale: 'menu.devices.diagnostics', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'provisioning',
        name: 'DeviceProvisioning',
        component: () => import('@/views/DeviceProvisioning.vue'),
        meta: { locale: 'menu.devices.provisioning', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'grouping',
        name: 'DeviceGrouping',
        component: () => import('@/views/DeviceGrouping.vue'),
        meta: { locale: 'menu.devices.grouping', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'remote',
        name: 'RemoteControl',
        component: () => import('@/views/RemoteControl.vue'),
        meta: { locale: 'menu.devices.remote', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/pets',
    name: 'Pets',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.pets',
      requiresAuth: true,
      icon: 'icon-heart',
      order: 1,
    },
    children: [
      { path: '', redirect: '/pets/list', meta: { hideInMenu: true }},
      {
        path: 'list',
        name: 'PetList',
        component: () => import('@/views/PetsView.vue'),
        meta: { locale: 'menu.pets.list', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'profile/:id?',
        name: 'PetProfile',
        component: () => import('@/views/Pet360Profile.vue'),
        meta: { locale: 'menu.pets.profile', requiresAuth: true, roles: ['*'], hideInMenu: true },
      },
      {
        path: 'config/:id?',
        name: 'PetConfig',
        component: () => import('@/views/PetDetail.vue'),
        meta: { locale: 'menu.pets.config', requiresAuth: true, roles: ['*'], hideInMenu: true },
      },
      {
        path: 'family',
        name: 'PetFamily',
        component: () => import('@/views/FamilyMembers.vue'),
        meta: { locale: 'menu.pets.family', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'social',
        name: 'PetSocial',
        component: () => import('@/views/PetSocial.vue'),
        meta: { locale: 'menu.pets.social', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'insurance',
        name: 'PetInsurance',
        component: () => import('@/views/InsuranceView.vue'),
        meta: { locale: 'menu.pets.insurance', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'digital-twin',
        name: 'DigitalTwin',
        component: () => import('@/views/DigitalTwin.vue'),
        meta: { locale: 'menu.pets.digitalTwin', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'health',
        name: 'PetHealth',
        component: () => import('@/views/HealthTrackingView.vue'),
        meta: { locale: 'menu.pets.health', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'memory',
        name: 'PetMemory',
        component: () => import('@/views/PetMemory.vue'),
        meta: { locale: 'menu.pets.memory', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'interactions',
        name: 'PetInteractions',
        component: () => import('@/views/PetInteractions.vue'),
        meta: { locale: 'menu.pets.interactions', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'sleep',
        name: 'SleepAnalysis',
        component: () => import('@/views/SleepAnalysis.vue'),
        meta: { locale: 'menu.pets.sleep', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'nutrition',
        name: 'NutritionRecords',
        component: () => import('@/views/NutritionRecords.vue'),
        meta: { locale: 'menu.pets.nutrition', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'weight',
        name: 'WeightTracking',
        component: () => import('@/views/WeightTracking.vue'),
        meta: { locale: 'menu.pets.weight', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'album',
        name: 'FamilyAlbum',
        component: () => import('@/views/FamilyAlbum.vue'),
        meta: { locale: 'menu.pets.album', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'market',
        name: 'Marketplace',
        component: () => import('@/views/Marketplace.vue'),
        meta: { locale: 'menu.pets.market', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'medical',
        name: 'ThirdPartyMedical',
        component: () => import('@/views/ThirdPartyMedical.vue'),
        meta: { locale: 'menu.pets.medical', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'actions',
        name: 'ActionLibrary',
        component: () => import('@/views/ActionLibrary.vue'),
        meta: { locale: 'menu.pets.actions', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'voices',
        name: 'VoiceCustomization',
        component: () => import('@/views/VoiceCustomization.vue'),
        meta: { locale: 'menu.pets.voices', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'social-sharing',
        name: 'SocialSharing',
        component: () => import('@/views/SocialSharing.vue'),
        meta: { locale: 'menu.pets.socialSharing', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'breeding',
        name: 'PetBreeding',
        component: () => import('@/views/PetBreeding.vue'),
        meta: { locale: 'menu.pets.breeding', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'gallery',
        name: 'PetGallery',
        component: () => import('@/views/PetGallery.vue'),
        meta: { locale: 'menu.pets.gallery', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'training',
        name: 'PetTraining',
        component: () => import('@/views/PetTraining.vue'),
        meta: { locale: 'menu.pets.training', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'health',
        name: 'HealthRecords',
        component: () => import('@/views/HealthRecords.vue'),
        meta: { locale: 'menu.pets.health', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/child-mode',
    name: 'ChildMode',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.childMode',
      requiresAuth: true,
      icon: 'icon-heart',
      order: 1,
    },
    children: [
      { path: '',
        redirect: '/child-mode/settings',
        meta: { hideInMenu: true },
      },
      {
        path: 'settings',
        name: 'ChildModeSettings',
        component: () => import('@/views/ChildMode.vue'),
        meta: { locale: 'menu.childMode', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/elder-care',
    name: 'ElderCare',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.elderCare',
      requiresAuth: true,
      icon: 'icon-heart',
      order: 1,
    },
    children: [
      { path: '',
        redirect: '/elder-care/settings',
        meta: { hideInMenu: true },
      },
      {
        path: 'settings',
        name: 'ElderCareSettings',
        component: () => import('@/views/ElderCareMode.vue'),
        meta: { locale: 'menu.elderCare', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/orders',
    name: 'Orders',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.orders',
      requiresAuth: true,
      icon: 'icon-shopping-cart',
      order: 1,
    },
    children: [
      {
        path: 'list',
        name: 'OrderList',
        component: () => import('@/views/OrdersView.vue'),
        meta: { locale: 'menu.orders.list', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/roles',
    name: 'Roles',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.roles',
      requiresAuth: true,
      icon: 'icon-team',
      order: 1,
    },
    children: [
      { path: '',
        redirect: '/roles/list',
        meta: { hideInMenu: true },
      },
      {
        path: 'list',
        name: 'RoleList',
        component: () => import('@/views/RolesView.vue'),
        meta: { locale: 'menu.roles.list', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/permissions',
    name: 'Permissions',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.permissions',
      requiresAuth: true,
      icon: 'icon-safe',
      order: 1,
    },
    children: [
      { path: '',
        redirect: '/permissions/list',
        meta: { hideInMenu: true },
      },
      {
        path: 'list',
        name: 'PermissionList',
        component: () => import('@/views/PermissionsView.vue'),
        meta: { locale: 'menu.permissions.list', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/alerts',
    name: 'Alerts',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.alerts',
      requiresAuth: true,
      icon: 'icon-warning',
      order: 1,
    },
    children: [
      { path: '',
        redirect: '/alerts/list',
        meta: { hideInMenu: true },
      },
      {
        path: 'list',
        name: 'AlertList',
        component: () => import('@/views/AlertsView.vue'),
        meta: { locale: 'menu.alerts.list', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'rules',
        name: 'AlertRules',
        component: () => import('@/views/AlertRulesView.vue'),
        meta: { locale: 'menu.alerts.rules', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'upgrade',
        name: 'AlertUpgrade',
        component: () => import('@/views/AlertUpgrade.vue'),
        meta: { locale: 'menu.alerts.upgrade', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'emotion',
        name: 'EmotionRecords',
        component: () => import('@/views/EmotionRecords.vue'),
        meta: { locale: 'menu.alerts.emotion', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/ota',
    name: 'OTA',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.ota',
      requiresAuth: true,
      icon: 'icon-upload',
      order: 1,
    },
    children: [
      { path: '',
        redirect: '/ota/list',
        meta: { hideInMenu: true },
      },
      {
        path: 'list',
        name: 'OTAList',
        component: () => import('@/views/OTAView.vue'),
        meta: { locale: 'menu.ota.list', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'matrix',
        name: 'FirmwareMatrix',
        component: () => import('@/views/FirmwareMatrix.vue'),
        meta: { locale: 'menu.ota.matrix', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'gray',
        name: 'OTAGrayDeploy',
        component: () => import('@/views/OTAGrayDeploy.vue'),
        meta: { locale: 'menu.ota.gray', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'repository',
        name: 'FirmwareRepository',
        component: () => import('@/views/FirmwareRepository.vue'),
        meta: { locale: 'menu.ota.repository', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/ai',
    name: 'AI',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.ai',
      requiresAuth: true,
      icon: 'icon-robot',
      order: 1,
    },
    children: [
      {
        path: 'models',
        name: 'AIModels',
        component: () => import('@/views/AIModelsView.vue'),
        meta: { locale: 'menu.ai.models', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'monitor',
        name: 'AIMonitor',
        component: () => import('@/views/AIMonitor.vue'),
        meta: { locale: 'menu.ai.monitor', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'knowledge',
        name: 'KnowledgeBase',
        component: () => import('@/views/KnowledgeBase.vue'),
        meta: { locale: 'menu.ai.knowledge', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'model-versions',
        name: 'ModelVersionManage',
        component: () => import('@/views/ModelVersionManage.vue'),
        meta: { locale: 'menu.ai.modelVersions', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'training',
        name: 'AITrainingTasks',
        component: () => import('@/views/AITrainingTasks.vue'),
        meta: { locale: 'menu.ai.training', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'decision-logs',
        name: 'AIDecisionLogs',
        component: () => import('@/views/AIDecisionLogs.vue'),
        meta: { locale: 'menu.ai.decisionLogs', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'fairness',
        name: 'AIFairness',
        component: () => import('@/views/AIFairness.vue'),
        meta: { locale: 'menu.ai.fairness', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'security-audit',
        name: 'SecurityAudit',
        component: () => import('@/views/SecurityAudit.vue'),
        meta: { locale: 'menu.ai.securityAudit', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'multi-pet',
        name: 'MultiPetCollaboration',
        component: () => import('@/views/MultiPetCollaboration.vue'),
        meta: { locale: 'menu.ai.multiPet', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'behavior',
        name: 'BehaviorAnalysis',
        component: () => import('@/views/BehaviorAnalysis.vue'),
        meta: { locale: 'menu.ai.behavior', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/subscriptions',
    name: 'Subscriptions',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.subscriptions',
      requiresAuth: true,
      icon: 'icon-subscription',
      order: 1,
    },
    children: [
      { path: '',
        redirect: '/subscriptions/list',
        meta: { hideInMenu: true },
      },
      {
        path: 'list',
        name: 'SubscriptionList',
        component: () => import('@/views/SubscriptionsView.vue'),
        meta: { locale: 'menu.subscriptions.list', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'plans',
        name: 'SubscriptionPlans',
        component: () => import('@/views/SubscriptionPlans.vue'),
        meta: { locale: 'menu.subscriptions.plans', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'webhooks',
        name: 'WebhooksView',
        component: () => import('@/views/WebhooksView.vue'),
        meta: { locale: 'menu.subscriptions.webhooks', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'billing',
        name: 'BillingInvoices',
        component: () => import('@/views/BillingInvoices.vue'),
        meta: { locale: 'menu.subscriptions.billing', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'history',
        name: 'SubscriptionHistory',
        component: () => import('@/views/SubscriptHistory.vue'),
        meta: { locale: 'menu.subscriptions.history', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'widget-market',
        name: 'WidgetMarket',
        component: () => import('@/views/WidgetMarket.vue'),
        meta: { locale: 'menu.subscriptions.widgetMarket', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/tenants',
    name: 'Tenants',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.tenants',
      requiresAuth: true,
      icon: 'icon-building',
      order: 1,
    },
    children: [
      { path: '',
        redirect: '/tenants/list',
        meta: { hideInMenu: true },
      },
      {
        path: 'list',
        name: 'TenantList',
        component: () => import('@/views/TenantsView.vue'),
        meta: { locale: 'menu.tenants.list', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/notifications',
    name: 'Notifications',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.notifications',
      requiresAuth: true,
      icon: 'icon-message',
      order: 1,
    },
    children: [
      { path: '',
        redirect: '/notifications/list',
        meta: { hideInMenu: true },
      },
      {
        path: 'list',
        name: 'NotificationList',
        component: () => import('@/views/NotificationsView.vue'),
        meta: { locale: 'menu.notifications.list', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'channels',
        name: 'NotificationChannels',
        component: () => import('@/views/NotificationChannels.vue'),
        meta: { locale: 'menu.notifications.channels', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/system',
    name: 'System',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.system',
      requiresAuth: true,
      icon: 'icon-settings',
      order: 1,
    },
    children: [
      {
        path: 'users',
        name: 'SystemUsers',
        component: () => import('@/views/UsersView.vue'),
        meta: { locale: 'menu.system.users', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'settings',
        name: 'SystemSettings',
        component: () => import('@/views/SystemSettingsView.vue'),
        meta: { locale: 'menu.system.settings', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'dictionaries',
        name: 'Dictionaries',
        component: () => import('@/views/DictionariesView.vue'),
        meta: { locale: 'menu.system.dictionaries', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'departments',
        name: 'Departments',
        component: () => import('@/views/DepartmentsView.vue'),
        meta: { locale: 'menu.system.departments', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'logs',
        name: 'OperationLogs',
        component: () => import('@/views/OperationLogsView.vue'),
        meta: { locale: 'menu.system.logs', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'ldap',
        name: 'LDAPSettings',
        component: () => import('@/views/LDAPSettings.vue'),
        meta: { locale: 'menu.system.ldap', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'remote-wipe',
        name: 'RemoteWipe',
        component: () => import('@/views/RemoteWipe.vue'),
        meta: { locale: 'menu.system.remoteWipe', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'regions',
        name: 'RegionsConfig',
        component: () => import('@/views/RegionsConfig.vue'),
        meta: { locale: 'menu.system.regions', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'data-masking',
        name: 'DataMasking',
        component: () => import('@/views/DataMasking.vue'),
        meta: { locale: 'menu.system.dataMasking', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'audit-logs',
        name: 'AuditLogs',
        component: () => import('@/views/AuditLogs.vue'),
        meta: { locale: 'menu.system.auditLogs', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'i18n',
        name: 'Internationalization',
        component: () => import('@/views/Internationalization.vue'),
        meta: { locale: 'menu.system.i18n', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'edge-nodes',
        name: 'EdgeNodes',
        component: () => import('@/views/EdgeNodes.vue'),
        meta: { locale: 'menu.system.edgeNodes', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'rate-limit',
        name: 'APIRateLimit',
        component: () => import('@/views/APIRateLimit.vue'),
        meta: { locale: 'menu.system.rateLimit', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'certificates',
        name: 'Certificates',
        component: () => import('@/views/Certificates.vue'),
        meta: { locale: 'menu.system.certificates', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'smart-home',
        name: 'SmartHome',
        component: () => import('@/views/SmartHomeDevices.vue'),
        meta: { locale: 'menu.system.smartHome', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'simulation',
        name: 'Simulation',
        component: () => import('@/views/SimulationEnvironment.vue'),
        meta: { locale: 'menu.system.simulation', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'api-explorer',
        name: 'APIExplorer',
        component: () => import('@/views/APIExplorer.vue'),
        meta: { locale: 'menu.system.apiExplorer', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'pressure-test',
        name: 'PressureTesting',
        component: () => import('@/views/PressureTesting.vue'),
        meta: { locale: 'menu.system.pressureTest', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'ble-debug',
        name: 'BLEDebugging',
        component: () => import('@/views/BLEDebugging.vue'),
        meta: { locale: 'menu.system.bleDebug', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'dataset',
        name: 'DatasetManagement',
        component: () => import('@/views/DatasetManagement.vue'),
        meta: { locale: 'menu.system.dataset', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'cicd',
        name: 'CICDIntegration',
        component: () => import('@/views/CICDIntegration.vue'),
        meta: { locale: 'menu.system.cicd', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'compliance',
        name: 'DataCompliance',
        component: () => import('@/views/DataCompliance.vue'),
        meta: { locale: 'menu.system.compliance', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'offline-sync',
        name: 'OfflineSync',
        component: () => import('@/views/OfflineSync.vue'),
        meta: { locale: 'menu.system.offlineSync', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'notification',
        name: 'NotificationCenter',
        component: () => import('@/views/NotificationCenter.vue'),
        meta: { locale: 'menu.system.notification', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'data-export',
        name: 'DataExport',
        component: () => import('@/views/DataExport.vue'),
        meta: { locale: 'menu.system.dataExport', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'customer-service',
        name: 'CustomerService',
        component: () => import('@/views/CustomerService.vue'),
        meta: { locale: 'menu.system.customerService', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'product',
        name: 'ProductManagement',
        component: () => import('@/views/ProductManagement.vue'),
        meta: { locale: 'menu.system.product', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'price-strategy',
        name: 'PriceStrategy',
        component: () => import('@/views/PriceStrategy.vue'),
        meta: { locale: 'menu.system.priceStrategy', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'storage',
        name: 'StorageManagement',
        component: () => import('@/views/StorageManagement.vue'),
        meta: { locale: 'menu.system.storage', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'health',
        name: 'SystemHealth',
        component: () => import('@/views/SystemHealth.vue'),
        meta: { locale: 'menu.system.health', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'settings',
        name: 'SettingsCenter',
        component: () => import('@/views/SettingsCenter.vue'),
        meta: { locale: 'menu.system.settings', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'feedback',
        name: 'FeedbackManagement',
        component: () => import('@/views/FeedbackManagement.vue'),
        meta: { locale: 'menu.system.feedback', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/developer',
    name: 'Developer',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.developer',
      requiresAuth: true,
      icon: 'icon-code',
      order: 1,
    },
    children: [
      {
        path: 'apps',
        name: 'DevApps',
        component: () => import('@/views/DeveloperPortal.vue'),
        meta: { locale: 'menu.developer.apps', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'logs',
        name: 'DevLogs',
        component: () => import('@/views/APILogs.vue'),
        meta: { locale: 'menu.developer.logs', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'tokens',
        name: 'AccessTokenManagement',
        component: () => import('@/views/AccessTokenManagement.vue'),
        meta: { locale: 'menu.openplatform.tokens', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'webhooks',
        name: 'APIWebhooks',
        component: () => import('@/views/APIWebhooks.vue'),
        meta: { locale: 'menu.openplatform.webhooks', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'marketplace',
        name: 'AppMarketplace',
        component: () => import('@/views/AppMarketplace.vue'),
        meta: { locale: 'menu.openplatform.marketplace', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  },

  // ===== 新增模块路由 =====
  { path: '/advanced', name: 'Advanced', component: DEFAULT_LAYOUT, meta: { locale: 'menu.advanced', requiresAuth: true, icon: 'icon-tool', order: 2 }, children: [
      { path: '', redirect: '/advanced/child-mode', meta: { hideInMenu: true }},
      { path: 'child-mode', name: 'AdvancedChildMode', component: () => import('@/views/advanced/ChildModeView.vue'), meta: { locale: 'menu.advanced.childMode', requiresAuth: true, roles: ['*'] }},
      { path: 'elder-mode', name: 'AdvancedElderMode', component: () => import('@/views/advanced/ElderlyModeView.vue'), meta: { locale: 'menu.advanced.elderMode', requiresAuth: true, roles: ['*'] }},
      { path: 'family-album', name: 'AdvancedFamilyAlbum', component: () => import('@/views/advanced/FamilyAlbumView.vue'), meta: { locale: 'menu.advanced.familyAlbum', requiresAuth: true, roles: ['*'] }},
      { path: 'feature-config', name: 'AdvancedFeatureConfig', component: () => import('@/views/advanced/FeatureConfigView.vue'), meta: { locale: 'menu.advanced.featureConfig', requiresAuth: true, roles: ['*'] }},
      { path: 'device-certificates', name: 'AdvancedDeviceCerts', component: () => import('@/views/advanced/DeviceCertificates.vue'), meta: { locale: 'menu.advanced.deviceCertificates', requiresAuth: true, roles: ['*'] }},
      { path: 'diet-record', name: 'AdvancedDietRecord', component: () => import('@/views/advanced/DietRecordView.vue'), meta: { locale: 'menu.advanced.dietRecord', requiresAuth: true, roles: ['*'] }},
      { path: 'pet-finder', name: 'AdvancedPetFinder', component: () => import('@/views/advanced/PetFinderView.vue'), meta: { locale: 'menu.advanced.petFinder', requiresAuth: true, roles: ['*'] }},
      { path: 'vaccination', name: 'AdvancedVaccination', component: () => import('@/views/advanced/VaccinationView.vue'), meta: { locale: 'menu.advanced.vaccination', requiresAuth: true, roles: ['*']}},
    ],
  },
  { path: '/alert-detail', name: 'AlertDetail', component: DEFAULT_LAYOUT, meta: { locale: 'menu.alertDetail', requiresAuth: true, icon: 'icon-warning', order: 2 }, children: [
      { path: '', redirect: '/alert-detail/history', meta: { hideInMenu: true }},
      { path: 'history', name: 'AlertHistory', component: () => import('@/views/alert/AlertHistoryView.vue'), meta: { locale: 'menu.alertDetail.history', requiresAuth: true, roles: ['*'] }},
      { path: 'notification', name: 'AlertNotification', component: () => import('@/views/alert/AlertNotificationView.vue'), meta: { locale: 'menu.alertDetail.notification', requiresAuth: true, roles: ['*'] }},
      { path: 'email-channel', name: 'AlertEmailChannel', component: () => import('@/views/alert/EmailChannelConfig.vue'), meta: { locale: 'menu.alertDetail.emailChannel', requiresAuth: true, roles: ['*'] }},
      { path: 'sms-channel', name: 'AlertSMSChannel', component: () => import('@/views/alert/SMSChannelConfig.vue'), meta: { locale: 'menu.alertDetail.smsChannel', requiresAuth: true, roles: ['*'] }},
      { path: 'webhook-channel', name: 'AlertWebhookChannel', component: () => import('@/views/alert/WebhookChannelConfig.vue'), meta: { locale: 'menu.alertDetail.webhookChannel', requiresAuth: true, roles: ['*'] }},
      { path: 'notification-logs', name: 'AlertNotificationLogs', component: () => import('@/views/alert/NotificationLogsView.vue'), meta: { locale: 'menu.alertDetail.notificationLogs', requiresAuth: true, roles: ['*'] }},
      { path: 'notification-stats', name: 'AlertNotificationStats', component: () => import('@/views/alert/NotificationStatsView.vue'), meta: { locale: 'menu.alertDetail.notificationStats', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/analytics', name: 'Analytics', component: DEFAULT_LAYOUT, meta: { locale: 'menu.analytics', requiresAuth: true, icon: 'icon-chart', order: 2 }, children: [
      { path: '', redirect: '/analytics/cohort', meta: { hideInMenu: true }},
      { path: 'cohort', name: 'CohortAnalysis', component: () => import('@/views/analytics/CohortAnalysisView.vue'), meta: { locale: 'menu.analytics.cohort', requiresAuth: true, roles: ['*'] }},
      { path: 'event', name: 'EventAnalytics', component: () => import('@/views/analytics/EventAnalyticsView.vue'), meta: { locale: 'menu.analytics.event', requiresAuth: true, roles: ['*'] }},
      { path: 'funnel', name: 'FunnelAnalysis', component: () => import('@/views/analytics/FunnelAnalysisView.vue'), meta: { locale: 'menu.analytics.funnel', requiresAuth: true, roles: ['*'] }},
      { path: 'retention', name: 'RetentionAnalysis', component: () => import('@/views/analytics/RetentionAnalysisView.vue'), meta: { locale: 'menu.analytics.retention', requiresAuth: true, roles: ['*'] }},
      { path: 'dashboard', name: 'AnalyticsDashboard', component: () => import('@/views/analytics/DashboardView.vue'), meta: { locale: 'menu.analytics.dashboard', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/digital-twin', name: 'DigitalTwinModule', component: DEFAULT_LAYOUT, meta: { locale: 'menu.digitalTwin', requiresAuth: true, icon: 'icon-scan', order: 2 }, children: [
      { path: '', redirect: '/digital-twin/vitals', meta: { hideInMenu: true }},
      { path: 'vitals', name: 'VitalsDashboard', component: () => import('@/views/digital-twin/VitalsDashboardView.vue'), meta: { locale: 'menu.digitalTwin.vitals', requiresAuth: true, roles: ['*'] }},
      { path: 'realtime', name: 'RealTimeVitals', component: () => import('@/views/digital-twin/RealTimeVitalsChart.vue'), meta: { locale: 'menu.digitalTwin.realtime', requiresAuth: true, roles: ['*'] }},
      { path: 'moments', name: 'DigitalTwinMoments', component: () => import('@/views/digital-twin/MomentsView.vue'), meta: { locale: 'menu.digitalTwin.moments', requiresAuth: true, roles: ['*'] }},
      { path: 'behavior-prediction', name: 'BehaviorPrediction', component: () => import('@/views/digital-twin/BehaviorPredictionView.vue'), meta: { locale: 'menu.digitalTwin.behaviorPrediction', requiresAuth: true, roles: ['*'] }},
      { path: 'historical-replay', name: 'HistoricalReplay', component: () => import('@/views/digital-twin/HistoricalReplayView.vue'), meta: { locale: 'menu.digitalTwin.historicalReplay', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/emotion', name: 'Emotion', component: DEFAULT_LAYOUT, meta: { locale: 'menu.emotion', requiresAuth: true, icon: 'icon-heart', order: 2 }, children: [
      { path: '', redirect: '/emotion/log', meta: { hideInMenu: true }},
      { path: 'log', name: 'EmotionLog', component: () => import('@/views/emotion/EmotionLogView.vue'), meta: { locale: 'menu.emotion.log', requiresAuth: true, roles: ['*'] }},
      { path: 'recognize', name: 'EmotionRecognize', component: () => import('@/views/emotion/EmotionRecognizeView.vue'), meta: { locale: 'menu.emotion.recognize', requiresAuth: true, roles: ['*'] }},
      { path: 'report', name: 'EmotionReport', component: () => import('@/views/emotion/EmotionReportView.vue'), meta: { locale: 'menu.emotion.report', requiresAuth: true, roles: ['*'] }},
      { path: 'trend', name: 'EmotionTrend', component: () => import('@/views/emotion/EmotionTrendView.vue'), meta: { locale: 'menu.emotion.trend', requiresAuth: true, roles: ['*'] }},
      { path: 'response-config', name: 'EmotionResponseConfig', component: () => import('@/views/emotion/EmotionResponseConfigView.vue'), meta: { locale: 'menu.emotion.responseConfig', requiresAuth: true, roles: ['*'] }},
      { path: 'family-map', name: 'FamilyEmotionMap', component: () => import('@/views/emotion/FamilyEmotionMapView.vue'), meta: { locale: 'menu.emotion.familyMap', requiresAuth: true, roles: ['*'] }},
      { path: 'voice', name: 'VoiceEmotion', component: () => import('@/views/emotion/VoiceEmotionView.vue'), meta: { locale: 'menu.emotion.voice', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/embodied', name: 'Embodied', component: DEFAULT_LAYOUT, meta: { locale: 'menu.embodied', requiresAuth: true, icon: 'icon-robot', order: 2 }, children: [
      { path: '', redirect: '/embodied/action', meta: { hideInMenu: true }},
      { path: 'action', name: 'ActionLibrary', component: () => import('@/views/embodied/ActionLibraryView.vue'), meta: { locale: 'menu.embodied.action', requiresAuth: true, roles: ['*'] }},
      { path: 'decision-logs', name: 'EmbodiedDecisionLogs', component: () => import('@/views/embodied/DecisionLogsView.vue'), meta: { locale: 'menu.embodied.decisionLogs', requiresAuth: true, roles: ['*'] }},
      { path: 'map', name: 'EmbodiedMap', component: () => import('@/views/embodied/MapView.vue'), meta: { locale: 'menu.embodied.map', requiresAuth: true, roles: ['*'] }},
      { path: 'navigation', name: 'EmbodiedNavigation', component: () => import('@/views/embodied/NavigationView.vue'), meta: { locale: 'menu.embodied.navigation', requiresAuth: true, roles: ['*'] }},
      { path: 'perception', name: 'EmbodiedPerception', component: () => import('@/views/embodied/PerceptionView.vue'), meta: { locale: 'menu.embodied.perception', requiresAuth: true, roles: ['*'] }},
      { path: 'safety-zones', name: 'SafetyZones', component: () => import('@/views/embodied/SafetyZonesView.vue'), meta: { locale: 'menu.embodied.safetyZones', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/ai-fairness', name: 'AIFairnessModule', component: DEFAULT_LAYOUT, meta: { locale: 'menu.aiFairness', requiresAuth: true, icon: 'icon-robot', order: 2 }, children: [
      { path: '', redirect: '/ai-fairness/report', meta: { hideInMenu: true }},
      { path: 'report', name: 'FairnessReport', component: () => import('@/views/ai-fairness/FairnessReportView.vue'), meta: { locale: 'menu.aiFairness.report', requiresAuth: true, roles: ['*'] }},
      { path: 'test', name: 'FairnessTest', component: () => import('@/views/ai-fairness/FairnessTestView.vue'), meta: { locale: 'menu.aiFairness.test', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/simulation', name: 'SimulationModule', component: DEFAULT_LAYOUT, meta: { locale: 'menu.simulation', requiresAuth: true, icon: 'icon-simulation', order: 2 }, children: [
      { path: '', redirect: '/simulation/ab', meta: { hideInMenu: true }},
      { path: 'ab', name: 'ABExperiment', component: () => import('@/views/simulation/ABExperimentView.vue'), meta: { locale: 'menu.simulation.ab', requiresAuth: true, roles: ['*'] }},
      { path: 'replay', name: 'SimulationReplay', component: () => import('@/views/simulation/ReplayView.vue'), meta: { locale: 'menu.simulation.replay', requiresAuth: true, roles: ['*'] }},
      { path: 'recordings', name: 'SimulationRecordings', component: () => import('@/views/simulation/SimulationRecordingsView.vue'), meta: { locale: 'menu.simulation.recordings', requiresAuth: true, roles: ['*'] }},
      { path: 'scenes', name: 'SimulationScenes', component: () => import('@/views/simulation/SimulationScenesView.vue'), meta: { locale: 'menu.simulation.scenes', requiresAuth: true, roles: ['*'] }},
      { path: 'stress', name: 'StressTest', component: () => import('@/views/simulation/StressTestView.vue'), meta: { locale: 'menu.simulation.stress', requiresAuth: true, roles: ['*'] }},
      { path: 'framework', name: 'TestFramework', component: () => import('@/views/simulation/TestFrameworkView.vue'), meta: { locale: 'menu.simulation.framework', requiresAuth: true, roles: ['*'] }},
      { path: 'virtual-pet', name: 'VirtualPetSimulation', component: () => import('@/views/simulation/VirtualPetSimulationView.vue'), meta: { locale: 'menu.simulation.virtualPet', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/platform-evo', name: 'PlatformEvo', component: DEFAULT_LAYOUT, meta: { locale: 'menu.platformEvo', requiresAuth: true, icon: 'icon-up', order: 2 }, children: [
      { path: '', redirect: '/platform-evo/edge', meta: { hideInMenu: true }},
      { path: 'edge', name: 'EdgeAI', component: () => import('@/views/platform-evo/EdgeAIView.vue'), meta: { locale: 'menu.platformEvo.edge', requiresAuth: true, roles: ['*'] }},
      { path: 'model-shard', name: 'ModelShard', component: () => import('@/views/platform-evo/ModelShardView.vue'), meta: { locale: 'menu.platformEvo.modelShard', requiresAuth: true, roles: ['*'] }},
      { path: 'ble-mesh', name: 'BLEMesh', component: () => import('@/views/platform-evo/BLEMeshView.vue'), meta: { locale: 'menu.platformEvo.bleMesh', requiresAuth: true, roles: ['*'] }},
      { path: 'rtos', name: 'RTOS', component: () => import('@/views/platform-evo/RTOSView.vue'), meta: { locale: 'menu.platformEvo.rtos', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/security-evo', name: 'SecurityEvo', component: DEFAULT_LAYOUT, meta: { locale: 'menu.securityEvo', requiresAuth: true, icon: 'icon-safe', order: 2 }, children: [
      { path: '', redirect: '/security-evo/audit', meta: { hideInMenu: true }},
      { path: 'audit', name: 'SecurityEvoAudit', component: () => import('@/views/security-evo/AuditLogView.vue'), meta: { locale: 'menu.securityEvo.audit', requiresAuth: true, roles: ['*'] }},
      { path: 'compliance', name: 'SecurityEvoCompliance', component: () => import('@/views/security-evo/ComplianceView.vue'), meta: { locale: 'menu.securityEvo.compliance', requiresAuth: true, roles: ['*'] }},
      { path: 'data-export', name: 'SecurityEvoDataExport', component: () => import('@/views/security-evo/DataExportView.vue'), meta: { locale: 'menu.securityEvo.dataExport', requiresAuth: true, roles: ['*'] }},
      { path: 'gdpr', name: 'GDPR', component: () => import('@/views/security-evo/GDPRView.vue'), meta: { locale: 'menu.securityEvo.gdpr', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/research', name: 'Research', component: DEFAULT_LAYOUT, meta: { locale: 'menu.research', requiresAuth: true, icon: 'icon-experiment', order: 2 }, children: [
      { path: '', redirect: '/research/dataset', meta: { hideInMenu: true }},
      { path: 'dataset', name: 'DatasetLibrary', component: () => import('@/views/research/DatasetLibraryView.vue'), meta: { locale: 'menu.research.dataset', requiresAuth: true, roles: ['*'] }},
      { path: 'dataset-detail', name: 'DatasetDetail', component: () => import('@/views/research/DatasetDetailView.vue'), meta: { locale: 'menu.research.datasetDetail', requiresAuth: true, roles: ['*'] }},
      { path: 'dataset-view', name: 'DatasetView', component: () => import('@/views/research/DatasetView.vue'), meta: { locale: 'menu.research.datasetView', requiresAuth: true, roles: ['*'] }},
      { path: 'experiment', name: 'ResearchExperiment', component: () => import('@/views/research/ExperimentView.vue'), meta: { locale: 'menu.research.experiment', requiresAuth: true, roles: ['*'] }},
      { path: 'experiment-run', name: 'ExperimentRun', component: () => import('@/views/research/ExperimentRunView.vue'), meta: { locale: 'menu.research.experimentRun', requiresAuth: true, roles: ['*'] }},
      { path: 'project', name: 'ResearchProject', component: () => import('@/views/research/ResearchProjectView.vue'), meta: { locale: 'menu.research.project', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/policies', name: 'Policies', component: DEFAULT_LAYOUT, meta: { locale: 'menu.policies', requiresAuth: true, icon: 'icon-shield', order: 2 }, children: [
      { path: '', redirect: '/policies/list', meta: { hideInMenu: true }},
      { path: 'list', name: 'PolicyList', component: () => import('@/views/policies/PolicyList.vue'), meta: { locale: 'menu.policies.list', requiresAuth: true, roles: ['*'] }},
      { path: 'compliance-rules', name: 'ComplianceRules', component: () => import('@/views/policies/ComplianceRules.vue'), meta: { locale: 'menu.policies.complianceRules', requiresAuth: true, roles: ['*'] }},
      { path: 'device-compliance', name: 'DeviceCompliance', component: () => import('@/views/policies/DeviceCompliance.vue'), meta: { locale: 'menu.policies.deviceCompliance', requiresAuth: true, roles: ['*'] }},
      { path: 'policy-audit', name: 'PolicyAudit', component: () => import('@/views/policies/PolicyAuditView.vue'), meta: { locale: 'menu.policies.policyAudit', requiresAuth: true, roles: ['*'] }},
      { path: 'policy-configs', name: 'PolicyConfigs', component: () => import('@/views/policies/PolicyConfigs.vue'), meta: { locale: 'menu.policies.policyConfigs', requiresAuth: true, roles: ['*'] }},
      { path: 'policy-distribution', name: 'PolicyDistribution', component: () => import('@/views/policies/PolicyDistributionView.vue'), meta: { locale: 'menu.policies.policyDistribution', requiresAuth: true, roles: ['*'] }},
      { path: 'policy-templates', name: 'PolicyTemplates', component: () => import('@/views/policies/PolicyTemplatesView.vue'), meta: { locale: 'menu.policies.policyTemplates', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/globalization', name: 'Globalization', component: DEFAULT_LAYOUT, meta: { locale: 'menu.globalization', requiresAuth: true, icon: 'icon-global', order: 2 }, children: [
      { path: '', redirect: '/globalization/language', meta: { hideInMenu: true }},
      { path: 'language', name: 'LanguagePack', component: () => import('@/views/globalization/LanguagePackView.vue'), meta: { locale: 'menu.globalization.language', requiresAuth: true, roles: ['*'] }},
      { path: 'region', name: 'RegionManage', component: () => import('@/views/globalization/RegionManageView.vue'), meta: { locale: 'menu.globalization.region', requiresAuth: true, roles: ['*'] }},
      { path: 'region-node', name: 'RegionNode', component: () => import('@/views/globalization/RegionNodeView.vue'), meta: { locale: 'menu.globalization.regionNode', requiresAuth: true, roles: ['*'] }},
      { path: 'region-sync', name: 'RegionSyncStatus', component: () => import('@/views/globalization/RegionSyncStatusView.vue'), meta: { locale: 'menu.globalization.regionSync', requiresAuth: true, roles: ['*'] }},
      { path: 'ai-node', name: 'RegionalAINode', component: () => import('@/views/globalization/RegionalAINodeView.vue'), meta: { locale: 'menu.globalization.aiNode', requiresAuth: true, roles: ['*'] }},
      { path: 'currency', name: 'CurrencySettings', component: () => import('@/views/globalization/CurrencySettingsView.vue'), meta: { locale: 'menu.globalization.currency', requiresAuth: true, roles: ['*'] }},
      { path: 'timezone', name: 'TimezoneSettings', component: () => import('@/views/globalization/TimezoneSettingsView.vue'), meta: { locale: 'menu.globalization.timezone', requiresAuth: true, roles: ['*'] }},
      { path: 'data-residency', name: 'DataResidency', component: () => import('@/views/globalization/DataResidencyView.vue'), meta: { locale: 'menu.globalization.dataResidency', requiresAuth: true, roles: ['*'] }},
      { path: 'content-delivery', name: 'ContentDelivery', component: () => import('@/views/globalization/ContentDeliveryView.vue'), meta: { locale: 'menu.globalization.contentDelivery', requiresAuth: true, roles: ['*'] }},
      { path: 'settings', name: 'GlobalizationSettings', component: () => import('@/views/globalization/GlobalizationSettingsView.vue'), meta: { locale: 'menu.globalization.settings', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/pet-social', name: 'PetSocialModule', component: DEFAULT_LAYOUT, meta: { locale: 'menu.petSocial', requiresAuth: true, icon: 'icon-heart', order: 2 }, children: [
      { path: '', redirect: '/pet-social/follow', meta: { hideInMenu: true }},
      { path: 'follow', name: 'PetSocialFollow', component: () => import('@/views/pet-social/FollowView.vue'), meta: { locale: 'menu.petSocial.follow', requiresAuth: true, roles: ['*'] }},
      { path: 'moments', name: 'PetSocialMoments', component: () => import('@/views/pet-social/MomentsView.vue'), meta: { locale: 'menu.petSocial.moments', requiresAuth: true, roles: ['*'] }},
      { path: 'like-records', name: 'PetSocialLikeRecords', component: () => import('@/views/pet-social/LikeRecordView.vue'), meta: { locale: 'menu.petSocial.likeRecords', requiresAuth: true, roles: ['*'] }},
      { path: 'pet-feed', name: 'PetSocialPetFeed', component: () => import('@/views/pet-social/PetFeedView.vue'), meta: { locale: 'menu.petSocial.petFeed', requiresAuth: true, roles: ['*'] }},
      { path: 'pet-follow', name: 'PetSocialPetFollow', component: () => import('@/views/pet-social/PetFollowView.vue'), meta: { locale: 'menu.petSocial.petFollow', requiresAuth: true, roles: ['*'] }},
      { path: 'playdate', name: 'PetSocialPlaydate', component: () => import('@/views/pet-social/PetPlaydateView.vue'), meta: { locale: 'menu.petSocial.playdate', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/pet-console', name: 'PetConsoleModule', component: DEFAULT_LAYOUT, meta: { locale: 'menu.petConsole', requiresAuth: true, icon: 'icon-heart', order: 2 }, children: [
      { path: '', redirect: '/pet-console/console', meta: { hideInMenu: true }},
      { path: 'console', name: 'PetConsole', component: () => import('@/views/pet/PetConsole.vue'), meta: { locale: 'menu.petConsole.console', requiresAuth: true, roles: ['*'] }},
      { path: 'conversations', name: 'PetConversations', component: () => import('@/views/pet/PetConversations.vue'), meta: { locale: 'menu.petConsole.conversations', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/device-manage', name: 'DeviceManage', component: DEFAULT_LAYOUT, meta: { locale: 'menu.deviceManage', requiresAuth: true, icon: 'icon-device', order: 2 }, children: [
      { path: '', redirect: '/device-manage/certificates', meta: { hideInMenu: true }},
      { path: 'certificates', name: 'DeviceCertificates', component: () => import('@/views/devices/DeviceCertificates.vue'), meta: { locale: 'menu.deviceManage.certificates', requiresAuth: true, roles: ['*'] }},
      { path: 'geofence', name: 'DeviceGeofence', component: () => import('@/views/devices/DeviceGeofence.vue'), meta: { locale: 'menu.deviceManage.geofence', requiresAuth: true, roles: ['*'] }},
      { path: 'monitor-panel', name: 'DeviceMonitorPanel', component: () => import('@/views/devices/DeviceMonitorPanel.vue'), meta: { locale: 'menu.deviceManage.monitorPanel', requiresAuth: true, roles: ['*'] }},
      { path: 'remote-control', name: 'DeviceRemoteControl', component: () => import('@/views/devices/DeviceRemoteControl.vue'), meta: { locale: 'menu.deviceManage.remoteControl', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/ota-manage', name: 'OTAManage', component: DEFAULT_LAYOUT, meta: { locale: 'menu.otaManage', requiresAuth: true, icon: 'icon-upload', order: 2 }, children: [
      { path: '', redirect: '/ota-manage/packages', meta: { hideInMenu: true }},
      { path: 'packages', name: 'OTAPackages', component: () => import('@/views/ota/OtaPackages.vue'), meta: { locale: 'menu.otaManage.packages', requiresAuth: true, roles: ['*'] }},
      { path: 'deployments', name: 'OTADeployments', component: () => import('@/views/ota/OtaDeployments.vue'), meta: { locale: 'menu.otaManage.deployments', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/marketing', name: 'Marketing', component: DEFAULT_LAYOUT, meta: { locale: 'menu.marketing', requiresAuth: true, icon: 'icon-promotion', order: 2 }, children: [
      { path: '', redirect: '/marketing/redpacket', meta: { hideInMenu: true }},
      { path: 'redpacket', name: 'MarketingRedpacket', component: () => import('@/views/marketing/RedpacketView.vue'), meta: { locale: 'menu.marketing.redpacket', requiresAuth: true, roles: ['*'] }},
      { path: 'temp-coupon', name: 'TempCouponGrant', component: () => import('@/views/marketing/TempCouponGrantView.vue'), meta: { locale: 'menu.marketing.tempCoupon', requiresAuth: true, roles: ['*'] }},
      { path: 'temp-coupons', name: 'TempCoupons', component: () => import('@/views/marketing/TempCoupons.vue'), meta: { locale: 'menu.marketing.tempCoupons', requiresAuth: true, roles: ['*'] }},
      { path: 'temp-redpacket', name: 'TempRedpacket', component: () => import('@/views/marketing/TempRedpacketView.vue'), meta: { locale: 'menu.marketing.tempRedpacket', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/market', name: 'Market', component: DEFAULT_LAYOUT, meta: { locale: 'menu.market', requiresAuth: true, icon: 'icon-shopping-cart', order: 2 }, children: [
      { path: '', redirect: '/market/action', meta: { hideInMenu: true }},
      { path: 'action', name: 'ActionMarket', component: () => import('@/views/market/ActionMarketView.vue'), meta: { locale: 'menu.market.action', requiresAuth: true, roles: ['*'] }},
      { path: 'ad-campaign', name: 'AdCampaign', component: () => import('@/views/market/AdCampaignView.vue'), meta: { locale: 'menu.market.adCampaign', requiresAuth: true, roles: ['*'] }},
      { path: 'content-review', name: 'ContentReview', component: () => import('@/views/market/ContentReviewView.vue'), meta: { locale: 'menu.market.contentReview', requiresAuth: true, roles: ['*'] }},
      { path: 'coupon-pool', name: 'CouponPool', component: () => import('@/views/market/CouponPoolView.vue'), meta: { locale: 'menu.market.couponPool', requiresAuth: true, roles: ['*'] }},
      { path: 'emoticon', name: 'EmoticonMarket', component: () => import('@/views/market/EmoticonMarketView.vue'), meta: { locale: 'menu.market.emoticon', requiresAuth: true, roles: ['*'] }},
      { path: 'recharge', name: 'MarketRecharge', component: () => import('@/views/market/RechargeRulesView.vue'), meta: { locale: 'menu.market.recharge', requiresAuth: true, roles: ['*'] }},
      { path: 'voice', name: 'MarketVoice', component: () => import('@/views/market/VoiceConfigView.vue'), meta: { locale: 'menu.market.voice', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/knowledge', name: 'Knowledge', component: DEFAULT_LAYOUT, meta: { locale: 'menu.knowledge', requiresAuth: true, icon: 'icon-book', order: 2 }, children: [
      { path: '', redirect: '/knowledge/list', meta: { hideInMenu: true }},
      { path: 'list', name: 'KnowledgeList', component: () => import('@/views/knowledge/KnowledgeList.vue'), meta: { locale: 'menu.knowledge.list', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/org', name: 'Org', component: DEFAULT_LAYOUT, meta: { locale: 'menu.org', requiresAuth: true, icon: 'icon-tree', order: 2 }, children: [
      { path: '', redirect: '/org/companies', meta: { hideInMenu: true }},
      { path: 'companies', name: 'Companies', component: () => import('@/views/org/Companies.vue'), meta: { locale: 'menu.org.companies', requiresAuth: true, roles: ['*'] }},
      { path: 'departments', name: 'OrgDepartments', component: () => import('@/views/org/Departments.vue'), meta: { locale: 'menu.org.departments', requiresAuth: true, roles: ['*'] }},
      { path: 'employees', name: 'OrgEmployees', component: () => import('@/views/org/Employees.vue'), meta: { locale: 'menu.org.employees', requiresAuth: true, roles: ['*'] }},
      { path: 'posts', name: 'OrgPosts', component: () => import('@/views/org/Posts.vue'), meta: { locale: 'menu.org.posts', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/permission-manage', name: 'PermissionManage', component: DEFAULT_LAYOUT, meta: { locale: 'menu.permissionManage', requiresAuth: true, icon: 'icon-safe', order: 2 }, children: [
      { path: '', redirect: '/permission-manage/api', meta: { hideInMenu: true }},
      { path: 'api', name: 'ApiPermissions', component: () => import('@/views/permissions/ApiPermissions.vue'), meta: { locale: 'menu.permissionManage.api', requiresAuth: true, roles: ['*'] }},
      { path: 'data-config', name: 'DataPermissionConfig', component: () => import('@/views/permissions/DataPermissionConfig.vue'), meta: { locale: 'menu.permissionManage.dataConfig', requiresAuth: true, roles: ['*'] }},
      { path: 'menus', name: 'PermissionMenus', component: () => import('@/views/permissions/Menus.vue'), meta: { locale: 'menu.permissionManage.menus', requiresAuth: true, roles: ['*'] }},
      { path: 'groups', name: 'PermissionGroups', component: () => import('@/views/permissions/PermissionGroups.vue'), meta: { locale: 'menu.permissionManage.groups', requiresAuth: true, roles: ['*'] }},
      { path: 'roles', name: 'PermissionRoles', component: () => import('@/views/permissions/Roles.vue'), meta: { locale: 'menu.permissionManage.roles', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/store', name: 'Store', component: DEFAULT_LAYOUT, meta: { locale: 'menu.store', requiresAuth: true, icon: 'icon-shopping-cart', order: 2 }, children: [
      { path: '', redirect: '/store/promotion', meta: { hideInMenu: true }},
      { path: 'promotion', name: 'StorePromotion', component: () => import('@/views/store/PromotionTypesView.vue'), meta: { locale: 'menu.store.promotion', requiresAuth: true, roles: ['*'] }},
      { path: 'locations', name: 'StoreLocations', component: () => import('@/views/store/StoreLocationsView.vue'), meta: { locale: 'menu.store.locations', requiresAuth: true, roles: ['*'] }},
      { path: 'sources', name: 'StoreSources', component: () => import('@/views/store/StoreSourcesView.vue'), meta: { locale: 'menu.store.sources', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/miniclaw', name: 'MiniClaw', component: DEFAULT_LAYOUT, meta: { locale: 'menu.miniclaw', requiresAuth: true, icon: 'icon-robot', order: 2 }, children: [
      { path: '', redirect: '/miniclaw/firmware', meta: { hideInMenu: true }},
      { path: 'firmware', name: 'MiniClawFirmware', component: () => import('@/views/miniclaw/FirmwareList.vue'), meta: { locale: 'menu.miniclaw.firmware', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/openplatform', name: 'OpenPlatform', component: DEFAULT_LAYOUT, meta: { locale: 'menu.openplatform', requiresAuth: true, icon: 'icon-code', order: 2 }, children: [
      { path: '', redirect: '/openplatform/agent', meta: { hideInMenu: true }},
      { path: 'agent', name: 'OpenPlatformAgent', component: () => import('@/views/platform/AgentView.vue'), meta: { locale: 'menu.openplatform.agent', requiresAuth: true, roles: ['*'] }},
      { path: 'ai-model-version', name: 'OpenPlatformAiModel', component: () => import('@/views/platform/AiModelVersionView.vue'), meta: { locale: 'menu.openplatform.aiModel', requiresAuth: true, roles: ['*'] }},
      { path: 'api-docs', name: 'OpenPlatformApiDocs', component: () => import('@/views/platform/ApiDocsView.vue'), meta: { locale: 'menu.openplatform.apiDocs', requiresAuth: true, roles: ['*'] }},
      { path: 'developer-console', name: 'OpenPlatformConsole', component: () => import('@/views/platform/DeveloperConsoleView.vue'), meta: { locale: 'menu.openplatform.console', requiresAuth: true, roles: ['*'] }},
      { path: 'webhook-market', name: 'OpenPlatformWebhook', component: () => import('@/views/platform/WebhookMarketView.vue'), meta: { locale: 'menu.openplatform.webhook', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/health', name: 'HealthModule', component: DEFAULT_LAYOUT, meta: { locale: 'menu.health', requiresAuth: true, icon: 'icon-heart', order: 2 }, children: [
      { path: '', redirect: '/health/report', meta: { hideInMenu: true }},
      { path: 'report', name: 'HealthReport', component: () => import('@/views/health/HealthReportView.vue'), meta: { locale: 'menu.health.report', requiresAuth: true, roles: ['*'] }},
      { path: 'warning', name: 'HealthWarning', component: () => import('@/views/health/HealthWarningView.vue'), meta: { locale: 'menu.health.warning', requiresAuth: true, roles: ['*'] }},
      { path: 'sleep', name: 'HealthSleep', component: () => import('@/views/health/SleepAnalysisView.vue'), meta: { locale: 'menu.health.sleep', requiresAuth: true, roles: ['*'] }},
      { path: 'exercise', name: 'HealthExercise', component: () => import('@/views/health/ExerciseStatsView.vue'), meta: { locale: 'menu.health.exercise', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/integration', name: 'Integration', component: DEFAULT_LAYOUT, meta: { locale: 'menu.integration', requiresAuth: true, icon: 'icon-link', order: 2 }, children: [
      { path: '', redirect: '/integration/smart-home', meta: { hideInMenu: true }},
      { path: 'smart-home', name: 'IntegrationSmartHome', component: () => import('@/views/integration/SmartHomeView.vue'), meta: { locale: 'menu.integration.smartHome', requiresAuth: true, roles: ['*'] }},
      { path: 'pet-hospital', name: 'IntegrationPetHospital', component: () => import('@/views/integration/PetHospitalView.vue'), meta: { locale: 'menu.integration.petHospital', requiresAuth: true, roles: ['*'] }},
      { path: 'pet-shop', name: 'IntegrationPetShop', component: () => import('@/views/integration/PetShopView.vue'), meta: { locale: 'menu.integration.petShop', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/content', name: 'Content', component: DEFAULT_LAYOUT, meta: { locale: 'menu.content', requiresAuth: true, icon: 'icon-file', order: 2 }, children: [
      { path: '', redirect: '/content/app-store', meta: { hideInMenu: true }},
      { path: 'app-store', name: 'ContentAppStore', component: () => import('@/views/content/AppStoreView.vue'), meta: { locale: 'menu.content.appStore', requiresAuth: true, roles: ['*'] }},
      { path: 'library', name: 'ContentLibrary', component: () => import('@/views/content/ContentLibraryView.vue'), meta: { locale: 'menu.content.library', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/offline', name: 'OfflineSupport', component: DEFAULT_LAYOUT, meta: { locale: 'menu.offline', requiresAuth: true, icon: 'icon-offline', order: 2 }, children: [
      { path: '', redirect: '/offline/sync', meta: { hideInMenu: true }},
      { path: 'sync', name: 'OfflineSyncView', component: () => import('@/views/offline/OfflineSyncView.vue'), meta: { locale: 'menu.offline.sync', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/billing', name: 'Billing', component: DEFAULT_LAYOUT, meta: { locale: 'menu.billing', requiresAuth: true, icon: 'icon-money', order: 2 }, children: [
      { path: '', redirect: '/billing/list', meta: { hideInMenu: true }},
      { path: 'list', name: 'BillingList', component: () => import('@/views/billing/BillingList.vue'), meta: { locale: 'menu.billing.list', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/app-manage', name: 'AppManage', component: DEFAULT_LAYOUT, meta: { locale: 'menu.appManage', requiresAuth: true, icon: 'icon-app', order: 2 }, children: [
      { path: '', redirect: '/app-manage/device', meta: { hideInMenu: true }},
      { path: 'device-control', name: 'AppDeviceControl', component: () => import('@/views/app/AppDeviceControlView.vue'), meta: { locale: 'menu.appManage.deviceControl', requiresAuth: true, roles: ['*'] }},
      { path: 'device-list', name: 'AppDeviceList', component: () => import('@/views/app/AppDeviceListView.vue'), meta: { locale: 'menu.appManage.deviceList', requiresAuth: true, roles: ['*'] }},
      { path: 'mini-home', name: 'MiniAppHome', component: () => import('@/views/app/MiniAppHomeView.vue'), meta: { locale: 'menu.appManage.miniHome', requiresAuth: true, roles: ['*'] }},
      { path: 'mini-device', name: 'MiniAppDevice', component: () => import('@/views/app/MiniAppDeviceView.vue'), meta: { locale: 'menu.appManage.miniDevice', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/apps', name: 'Apps', component: DEFAULT_LAYOUT, meta: { locale: 'menu.apps', requiresAuth: true, icon: 'icon-app', order: 2 }, children: [
      { path: '', redirect: '/apps/list', meta: { hideInMenu: true }},
      { path: 'list', name: 'AppList', component: () => import('@/views/apps/AppList.vue'), meta: { locale: 'menu.apps.list', requiresAuth: true, roles: ['*'] }},
      { path: 'distributions', name: 'AppDistributions', component: () => import('@/views/apps/AppDistributions.vue'), meta: { locale: 'menu.apps.distributions', requiresAuth: true, roles: ['*'] }},
      { path: 'versions', name: 'AppVersions', component: () => import('@/views/apps/AppVersions.vue'), meta: { locale: 'menu.apps.versions', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/security', name: 'SecurityModule', component: DEFAULT_LAYOUT, meta: { locale: 'menu.security', requiresAuth: true, icon: 'icon-safe', order: 2 }, children: [
      { path: '', redirect: '/security/audit', meta: { hideInMenu: true }},
      { path: 'audit', name: 'SecurityAuditLog', component: () => import('@/views/security/AuditLogView.vue'), meta: { locale: 'menu.security.audit', requiresAuth: true, roles: ['*'] }},
      { path: 'certificate', name: 'CertificateManage', component: () => import('@/views/security/CertificateManageView.vue'), meta: { locale: 'menu.security.certificate', requiresAuth: true, roles: ['*'] }},
      { path: 'data-permission', name: 'DataPermission', component: () => import('@/views/security/DataPermissionView.vue'), meta: { locale: 'menu.security.dataPermission', requiresAuth: true, roles: ['*'] }},
      { path: 'data-privacy', name: 'DataPrivacy', component: () => import('@/views/security/DataPrivacyView.vue'), meta: { locale: 'menu.security.dataPrivacy', requiresAuth: true, roles: ['*'] }},
      { path: 'device-security', name: 'DeviceSecurity', component: () => import('@/views/security/DeviceSecurityView.vue'), meta: { locale: 'menu.security.deviceSecurity', requiresAuth: true, roles: ['*'] }},
      { path: 'ldap', name: 'SecurityLDAP', component: () => import('@/views/security/LDAPConfigView.vue'), meta: { locale: 'menu.security.ldap', requiresAuth: true, roles: ['*'] }},
      { path: 'permission-assignment', name: 'PermissionAssignment', component: () => import('@/views/security/PermissionAssignmentView.vue'), meta: { locale: 'menu.security.permissionAssignment', requiresAuth: true, roles: ['*'] }},
      { path: 'user-sync', name: 'UserSync', component: () => import('@/views/security/UserSyncView.vue'), meta: { locale: 'menu.security.userSync', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/tenant-manage', name: 'TenantManage', component: DEFAULT_LAYOUT, meta: { locale: 'menu.tenantManage', requiresAuth: true, icon: 'icon-building', order: 2 }, children: [
      { path: '', redirect: '/tenant-manage/public', meta: { hideInMenu: true }},
      { path: 'public', name: 'TenantPublicArchives', component: () => import('@/views/tenants/PublicArchives.vue'), meta: { locale: 'menu.tenantManage.public', requiresAuth: true, roles: ['*'] }},
      { path: 'system-info', name: 'TenantSystemInfo', component: () => import('@/views/tenants/SystemInfo.vue'), meta: { locale: 'menu.tenantManage.systemInfo', requiresAuth: true, roles: ['*'] }},
      { path: 'application', name: 'TenantApplication', component: () => import('@/views/tenants/TenantApplication.vue'), meta: { locale: 'menu.tenantManage.application', requiresAuth: true, roles: ['*'] }},
      { path: 'approval', name: 'TenantApproval', component: () => import('@/views/tenants/TenantApproval.vue'), meta: { locale: 'menu.tenantManage.approval', requiresAuth: true, roles: ['*'] }},
      { path: 'management', name: 'TenantManagement', component: () => import('@/views/tenants/TenantManagement.vue'), meta: { locale: 'menu.tenantManage.management', requiresAuth: true, roles: ['*'] }},
      { path: 'settings', name: 'TenantSettings', component: () => import('@/views/tenants/TenantSettings.vue'), meta: { locale: 'menu.tenantManage.settings', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/notification-manage', name: 'NotificationManage', component: DEFAULT_LAYOUT, meta: { locale: 'menu.notificationManage', requiresAuth: true, icon: 'icon-message', order: 2 }, children: [
      { path: '', redirect: '/notification-manage/announcements', meta: { hideInMenu: true }},
      { path: 'announcements', name: 'NotificationAnnouncements', component: () => import('@/views/notifications/Announcements.vue'), meta: { locale: 'menu.notificationManage.announcements', requiresAuth: true, roles: ['*'] }},
      { path: 'list', name: 'NotificationListManage', component: () => import('@/views/notifications/NotificationList.vue'), meta: { locale: 'menu.notificationManage.list', requiresAuth: true, roles: ['*'] }},
      { path: 'templates', name: 'NotificationTemplates', component: () => import('@/views/notifications/NotificationTemplates.vue'), meta: { locale: 'menu.notificationManage.templates', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/subscription-manage', name: 'SubscriptionManage', component: DEFAULT_LAYOUT, meta: { locale: 'menu.subscriptionManage', requiresAuth: true, icon: 'icon-subscription', order: 2 }, children: [
      { path: '', redirect: '/subscription-manage/list', meta: { hideInMenu: true }},
      { path: 'list', name: 'SubscriptionListManage', component: () => import('@/views/subscription/SubscriptionList.vue'), meta: { locale: 'menu.subscriptionManage.list', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/member-manage', name: 'MemberManage', component: DEFAULT_LAYOUT, meta: { locale: 'menu.memberManage', requiresAuth: true, icon: 'icon-user', order: 2 }, children: [
      { path: '', redirect: '/member-manage/reception', meta: { hideInMenu: true }},
      { path: 'reception', name: 'MemberReception', component: () => import('@/views/member/MemberReception.vue'), meta: { locale: 'menu.memberManage.reception', requiresAuth: true, roles: ['*'] }},
      { path: 'settings', name: 'MemberSettingsManage', component: () => import('@/views/member/MemberSettings.vue'), meta: { locale: 'menu.memberManage.settings', requiresAuth: true, roles: ['*'] }},
      { path: 'articles', name: 'MemberArticles', component: () => import('@/views/member/MemberArticles.vue'), meta: { locale: 'menu.memberManage.articles', requiresAuth: true, roles: ['*'] }},
      { path: 'benefits', name: 'MemberBenefits', component: () => import('@/views/member/MemberBenefits.vue'), meta: { locale: 'menu.memberManage.benefits', requiresAuth: true, roles: ['*'] }},
      { path: 'gifts', name: 'MemberGifts', component: () => import('@/views/member/MemberGifts.vue'), meta: { locale: 'menu.memberManage.gifts', requiresAuth: true, roles: ['*'] }},
      { path: 'orders', name: 'MemberOrders', component: () => import('@/views/member/MemberOrders.vue'), meta: { locale: 'menu.memberManage.orders', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/webhooks', name: 'WebhookManage', component: DEFAULT_LAYOUT, meta: { locale: 'menu.webhooks', requiresAuth: true, icon: 'icon-link', order: 2 }, children: [
      { path: '', redirect: '/webhooks/list', meta: { hideInMenu: true }},
      { path: 'list', name: 'WebhookList', component: () => import('@/views/webhooks/WebhookList.vue'), meta: { locale: 'menu.webhooks.list', requiresAuth: true, roles: ['*'] }},
      { path: 'logs', name: 'WebhookLogs', component: () => import('@/views/webhooks/WebhookLogs.vue'), meta: { locale: 'menu.webhooks.logs', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/owner', name: 'Owner', component: DEFAULT_LAYOUT, meta: { locale: 'menu.owner', requiresAuth: true, icon: 'icon-user', order: 2 }, children: [
      { path: '', redirect: '/owner/profile', meta: { hideInMenu: true }},
      { path: 'profile', name: 'OwnerProfile', component: () => import('@/views/owner/OwnerProfile.vue'), meta: { locale: 'menu.owner.profile', requiresAuth: true, roles: ['*'] }},
    ],
  },
  { path: '/family', name: 'FamilyModule', component: DEFAULT_LAYOUT, meta: { locale: 'menu.family', requiresAuth: true, icon: 'icon-team', order: 2 }, children: [
      { path: '', redirect: '/family/members', meta: { hideInMenu: true }},
      { path: 'members', name: 'FamilyMembers', component: () => import('@/views/family/FamilyMembersView.vue'), meta: { locale: 'menu.family.members', requiresAuth: true, roles: ['*'] }},
      { path: 'settings', name: 'FamilySettings', component: () => import('@/views/family/FamilySettingsView.vue'), meta: { locale: 'menu.family.settings', requiresAuth: true, roles: ['*'] }},
    ],
  },
];

export default [DASHBOARD, ...MDM_ROUTES];
