import { DEFAULT_LAYOUT } from '../base';
import { AppRouteRecordRaw } from '../types';

const DASHBOARD: AppRouteRecordRaw = {
  path: '/dashboard',
  name: 'dashboard',
  component: DEFAULT_LAYOUT,
  meta: {
    locale: 'menu.dashboard',
    requiresAuth: true,
    icon: 'icon-dashboard',
    order: 0,
  },
  children: [
    {
      path: 'workplace',
      name: 'Workplace',
      component: () => import('@/views/dashboard/workplace/index.vue'),
      meta: {
        locale: 'menu.dashboard.workplace',
        requiresAuth: true,
        roles: ['*'],
      },
    },
    {
      path: 'monitor',
      name: 'Monitor',
      component: () => import('@/views/dashboard/monitor/index.vue'),
      meta: {
        locale: 'menu.dashboard.monitor',
        requiresAuth: true,
        roles: ['admin'],
      },
    },
  ],
};

// MDM 业务路由
const MDM_ROUTES: AppRouteRecordRaw[] = [
  {
    path: '/members',
    name: 'Members',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.members',
      requiresAuth: true,
      icon: 'icon-user',
      order: 1,
    },
    children: [
      { path: '', redirect: '/members/list' },
      {
        path: 'list',
        name: 'MemberList',
        component: () => import('@/views/members/MemberListView.vue'),
        meta: { locale: 'menu.members.list', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'points',
        name: 'MemberPoints',
        component: () => import('@/views/PointsRulesView.vue'),
        meta: { locale: 'menu.members.points', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'coupons',
        name: 'MemberCoupons',
        component: () => import('@/views/CouponsView.vue'),
        meta: { locale: 'menu.members.coupons', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'tags',
        name: 'MemberTags',
        component: () => import('@/views/MemberTags.vue'),
        meta: { locale: 'menu.members.tags', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'campaigns',
        name: 'Campaigns',
        component: () => import('@/views/Campaigns.vue'),
        meta: { locale: 'menu.members.campaigns', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'recharge',
        name: 'MemberRecharge',
        component: () => import('@/views/MemberRecharge.vue'),
        meta: { locale: 'menu.members.recharge', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'levels',
        name: 'MemberLevels',
        component: () => import('@/views/MemberLevels.vue'),
        meta: { locale: 'menu.members.levels', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'growth',
        name: 'MemberGrowth',
        component: () => import('@/views/MemberGrowth.vue'),
        meta: { locale: 'menu.members.growth', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'loyalty',
        name: 'LoyaltyProgram',
        component: () => import('@/views/LoyaltyProgram.vue'),
        meta: { locale: 'menu.members.loyalty', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'coupon-center',
        name: 'CouponCenter',
        component: () => import('@/views/CouponCenter.vue'),
        meta: { locale: 'menu.members.coupon', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/devices',
    name: 'Devices',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.devices',
      requiresAuth: true,
      icon: 'icon-device',
      order: 1,
    },
    children: [
      { path: '', redirect: '/devices/list' },
      {
        path: 'list',
        name: 'DeviceList',
        component: () => import('@/views/DeviceList.vue'),
        meta: { locale: 'menu.devices.list', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'detail/:id',
        name: 'DeviceDetail',
        component: () => import('@/views/DeviceDetail.vue'),
        meta: { locale: 'menu.devices.detail', requiresAuth: true, roles: ['*'], hideInMenu: true },
      },
      {
        path: 'pairing',
        name: 'DevicePairing',
        component: () => import('@/views/DevicePairing.vue'),
        meta: { locale: 'menu.devices.pairing', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'groups',
        name: 'DeviceGroups',
        component: () => import('@/views/DeviceGroupsView.vue'),
        meta: { locale: 'menu.devices.groups', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'commands',
        name: 'DeviceCommands',
        component: () => import('@/views/DeviceCommands.vue'),
        meta: { locale: 'menu.devices.commands', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'geofence',
        name: 'GeofenceConfig',
        component: () => import('@/views/GeofenceConfig.vue'),
        meta: { locale: 'menu.devices.geofence', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'geofencing',
        name: 'Geofencing',
        component: () => import('@/views/Geofencing.vue'),
        meta: { locale: 'menu.devices.geofencing', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'registration',
        name: 'DeviceRegistration',
        component: () => import('@/views/DeviceRegistration.vue'),
        meta: { locale: 'menu.devices.registration', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'diagnostics',
        name: 'DeviceDiagnostics',
        component: () => import('@/views/DeviceDiagnostics.vue'),
        meta: { locale: 'menu.devices.diagnostics', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'provisioning',
        name: 'DeviceProvisioning',
        component: () => import('@/views/DeviceProvisioning.vue'),
        meta: { locale: 'menu.devices.provisioning', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'grouping',
        name: 'DeviceGrouping',
        component: () => import('@/views/DeviceGrouping.vue'),
        meta: { locale: 'menu.devices.grouping', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'remote',
        name: 'RemoteControl',
        component: () => import('@/views/RemoteControl.vue'),
        meta: { locale: 'menu.devices.remote', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/pets',
    name: 'Pets',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.pets',
      requiresAuth: true,
      icon: 'icon-heart',
      order: 1,
    },
    children: [
      { path: '', redirect: '/pets/list' },
      {
        path: 'list',
        name: 'PetList',
        component: () => import('@/views/PetsView.vue'),
        meta: { locale: 'menu.pets.list', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'profile/:id?',
        name: 'PetProfile',
        component: () => import('@/views/Pet360Profile.vue'),
        meta: { locale: 'menu.pets.profile', requiresAuth: true, roles: ['*'], hideInMenu: true },
      },
      {
        path: 'config/:id?',
        name: 'PetConfig',
        component: () => import('@/views/PetDetail.vue'),
        meta: { locale: 'menu.pets.config', requiresAuth: true, roles: ['*'], hideInMenu: true },
      },
      {
        path: 'family',
        name: 'PetFamily',
        component: () => import('@/views/FamilyMembers.vue'),
        meta: { locale: 'menu.pets.family', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'social',
        name: 'PetSocial',
        component: () => import('@/views/PetSocial.vue'),
        meta: { locale: 'menu.pets.social', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'insurance',
        name: 'PetInsurance',
        component: () => import('@/views/InsuranceView.vue'),
        meta: { locale: 'menu.pets.insurance', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'digital-twin',
        name: 'DigitalTwin',
        component: () => import('@/views/DigitalTwin.vue'),
        meta: { locale: 'menu.pets.digitalTwin', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'health',
        name: 'PetHealth',
        component: () => import('@/views/HealthTrackingView.vue'),
        meta: { locale: 'menu.pets.health', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'memory',
        name: 'PetMemory',
        component: () => import('@/views/PetMemory.vue'),
        meta: { locale: 'menu.pets.memory', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'interactions',
        name: 'PetInteractions',
        component: () => import('@/views/PetInteractions.vue'),
        meta: { locale: 'menu.pets.interactions', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'sleep',
        name: 'SleepAnalysis',
        component: () => import('@/views/SleepAnalysis.vue'),
        meta: { locale: 'menu.pets.sleep', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'nutrition',
        name: 'NutritionRecords',
        component: () => import('@/views/NutritionRecords.vue'),
        meta: { locale: 'menu.pets.nutrition', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'weight',
        name: 'WeightTracking',
        component: () => import('@/views/WeightTracking.vue'),
        meta: { locale: 'menu.pets.weight', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'album',
        name: 'FamilyAlbum',
        component: () => import('@/views/FamilyAlbum.vue'),
        meta: { locale: 'menu.pets.album', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'market',
        name: 'Marketplace',
        component: () => import('@/views/Marketplace.vue'),
        meta: { locale: 'menu.pets.market', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'medical',
        name: 'ThirdPartyMedical',
        component: () => import('@/views/ThirdPartyMedical.vue'),
        meta: { locale: 'menu.pets.medical', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'actions',
        name: 'ActionLibrary',
        component: () => import('@/views/ActionLibrary.vue'),
        meta: { locale: 'menu.pets.actions', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'voices',
        name: 'VoiceCustomization',
        component: () => import('@/views/VoiceCustomization.vue'),
        meta: { locale: 'menu.pets.voices', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'social-sharing',
        name: 'SocialSharing',
        component: () => import('@/views/SocialSharing.vue'),
        meta: { locale: 'menu.pets.socialSharing', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'breeding',
        name: 'PetBreeding',
        component: () => import('@/views/PetBreeding.vue'),
        meta: { locale: 'menu.pets.breeding', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'gallery',
        name: 'PetGallery',
        component: () => import('@/views/PetGallery.vue'),
        meta: { locale: 'menu.pets.gallery', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'training',
        name: 'PetTraining',
        component: () => import('@/views/PetTraining.vue'),
        meta: { locale: 'menu.pets.training', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'health',
        name: 'HealthRecords',
        component: () => import('@/views/HealthRecords.vue'),
        meta: { locale: 'menu.pets.health', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/child-mode',
    name: 'ChildMode',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.childMode',
      requiresAuth: true,
      icon: 'icon-heart',
      order: 1,
    },
    children: [
      {
        path: '',
        redirect: '/child-mode/settings',
      },
      {
        path: 'settings',
        name: 'ChildModeSettings',
        component: () => import('@/views/ChildMode.vue'),
        meta: { locale: 'menu.childMode', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/elder-care',
    name: 'ElderCare',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.elderCare',
      requiresAuth: true,
      icon: 'icon-heart',
      order: 1,
    },
    children: [
      {
        path: '',
        redirect: '/elder-care/settings',
      },
      {
        path: 'settings',
        name: 'ElderCareSettings',
        component: () => import('@/views/ElderCareMode.vue'),
        meta: { locale: 'menu.elderCare', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/orders',
    name: 'Orders',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.orders',
      requiresAuth: true,
      icon: 'icon-shopping-cart',
      order: 1,
    },
    children: [
      {
        path: 'list',
        name: 'OrderList',
        component: () => import('@/views/OrdersView.vue'),
        meta: { locale: 'menu.orders.list', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/roles',
    name: 'Roles',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.roles',
      requiresAuth: true,
      icon: 'icon-team',
      order: 1,
    },
    children: [
      {
        path: '',
        redirect: '/roles/list',
      },
      {
        path: 'list',
        name: 'RoleList',
        component: () => import('@/views/RolesView.vue'),
        meta: { locale: 'menu.roles.list', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/permissions',
    name: 'Permissions',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.permissions',
      requiresAuth: true,
      icon: 'icon-safe',
      order: 1,
    },
    children: [
      {
        path: '',
        redirect: '/permissions/list',
      },
      {
        path: 'list',
        name: 'PermissionList',
        component: () => import('@/views/PermissionsView.vue'),
        meta: { locale: 'menu.permissions.list', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/alerts',
    name: 'Alerts',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.alerts',
      requiresAuth: true,
      icon: 'icon-warning',
      order: 1,
    },
    children: [
      {
        path: '',
        redirect: '/alerts/list',
      },
      {
        path: 'list',
        name: 'AlertList',
        component: () => import('@/views/AlertsView.vue'),
        meta: { locale: 'menu.alerts.list', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'rules',
        name: 'AlertRules',
        component: () => import('@/views/AlertRulesView.vue'),
        meta: { locale: 'menu.alerts.rules', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'upgrade',
        name: 'AlertUpgrade',
        component: () => import('@/views/AlertUpgrade.vue'),
        meta: { locale: 'menu.alerts.upgrade', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'emotion',
        name: 'EmotionRecords',
        component: () => import('@/views/EmotionRecords.vue'),
        meta: { locale: 'menu.alerts.emotion', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/ota',
    name: 'OTA',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.ota',
      requiresAuth: true,
      icon: 'icon-upload',
      order: 1,
    },
    children: [
      {
        path: '',
        redirect: '/ota/list',
      },
      {
        path: 'list',
        name: 'OTAList',
        component: () => import('@/views/OTAView.vue'),
        meta: { locale: 'menu.ota.list', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'matrix',
        name: 'FirmwareMatrix',
        component: () => import('@/views/FirmwareMatrix.vue'),
        meta: { locale: 'menu.ota.matrix', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'gray',
        name: 'OTAGrayDeploy',
        component: () => import('@/views/OTAGrayDeploy.vue'),
        meta: { locale: 'menu.ota.gray', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'repository',
        name: 'FirmwareRepository',
        component: () => import('@/views/FirmwareRepository.vue'),
        meta: { locale: 'menu.ota.repository', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/ai',
    name: 'AI',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.ai',
      requiresAuth: true,
      icon: 'icon-robot',
      order: 1,
    },
    children: [
      {
        path: 'models',
        name: 'AIModels',
        component: () => import('@/views/AIModelsView.vue'),
        meta: { locale: 'menu.ai.models', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'monitor',
        name: 'AIMonitor',
        component: () => import('@/views/AIMonitor.vue'),
        meta: { locale: 'menu.ai.monitor', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'knowledge',
        name: 'KnowledgeBase',
        component: () => import('@/views/KnowledgeBase.vue'),
        meta: { locale: 'menu.ai.knowledge', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'model-versions',
        name: 'ModelVersionManage',
        component: () => import('@/views/ModelVersionManage.vue'),
        meta: { locale: 'menu.ai.modelVersions', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'training',
        name: 'AITrainingTasks',
        component: () => import('@/views/AITrainingTasks.vue'),
        meta: { locale: 'menu.ai.training', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'decision-logs',
        name: 'AIDecisionLogs',
        component: () => import('@/views/AIDecisionLogs.vue'),
        meta: { locale: 'menu.ai.decisionLogs', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'fairness',
        name: 'AIFairness',
        component: () => import('@/views/AIFairness.vue'),
        meta: { locale: 'menu.ai.fairness', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'security-audit',
        name: 'SecurityAudit',
        component: () => import('@/views/SecurityAudit.vue'),
        meta: { locale: 'menu.ai.securityAudit', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'multi-pet',
        name: 'MultiPetCollaboration',
        component: () => import('@/views/MultiPetCollaboration.vue'),
        meta: { locale: 'menu.ai.multiPet', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'behavior',
        name: 'BehaviorAnalysis',
        component: () => import('@/views/BehaviorAnalysis.vue'),
        meta: { locale: 'menu.ai.behavior', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/subscriptions',
    name: 'Subscriptions',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.subscriptions',
      requiresAuth: true,
      icon: 'icon-subscription',
      order: 1,
    },
    children: [
      {
        path: '',
        redirect: '/subscriptions/list',
      },
      {
        path: 'list',
        name: 'SubscriptionList',
        component: () => import('@/views/SubscriptionsView.vue'),
        meta: { locale: 'menu.subscriptions.list', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'plans',
        name: 'SubscriptionPlans',
        component: () => import('@/views/SubscriptionPlans.vue'),
        meta: { locale: 'menu.subscriptions.plans', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'webhooks',
        name: 'WebhooksView',
        component: () => import('@/views/WebhooksView.vue'),
        meta: { locale: 'menu.subscriptions.webhooks', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'billing',
        name: 'BillingInvoices',
        component: () => import('@/views/BillingInvoices.vue'),
        meta: { locale: 'menu.subscriptions.billing', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'history',
        name: 'SubscriptionHistory',
        component: () => import('@/views/SubscriptHistory.vue'),
        meta: { locale: 'menu.subscriptions.history', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'widget-market',
        name: 'WidgetMarket',
        component: () => import('@/views/WidgetMarket.vue'),
        meta: { locale: 'menu.subscriptions.widgetMarket', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/tenants',
    name: 'Tenants',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.tenants',
      requiresAuth: true,
      icon: 'icon-building',
      order: 1,
    },
    children: [
      {
        path: '',
        redirect: '/tenants/list',
      },
      {
        path: 'list',
        name: 'TenantList',
        component: () => import('@/views/TenantsView.vue'),
        meta: { locale: 'menu.tenants.list', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/notifications',
    name: 'Notifications',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.notifications',
      requiresAuth: true,
      icon: 'icon-message',
      order: 1,
    },
    children: [
      {
        path: '',
        redirect: '/notifications/list',
      },
      {
        path: 'list',
        name: 'NotificationList',
        component: () => import('@/views/NotificationsView.vue'),
        meta: { locale: 'menu.notifications.list', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'channels',
        name: 'NotificationChannels',
        component: () => import('@/views/NotificationChannels.vue'),
        meta: { locale: 'menu.notifications.channels', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/system',
    name: 'System',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.system',
      requiresAuth: true,
      icon: 'icon-settings',
      order: 1,
    },
    children: [
      {
        path: 'users',
        name: 'SystemUsers',
        component: () => import('@/views/UsersView.vue'),
        meta: { locale: 'menu.system.users', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'settings',
        name: 'SystemSettings',
        component: () => import('@/views/SystemSettingsView.vue'),
        meta: { locale: 'menu.system.settings', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'dictionaries',
        name: 'Dictionaries',
        component: () => import('@/views/DictionariesView.vue'),
        meta: { locale: 'menu.system.dictionaries', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'departments',
        name: 'Departments',
        component: () => import('@/views/DepartmentsView.vue'),
        meta: { locale: 'menu.system.departments', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'logs',
        name: 'OperationLogs',
        component: () => import('@/views/OperationLogsView.vue'),
        meta: { locale: 'menu.system.logs', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'ldap',
        name: 'LDAPSettings',
        component: () => import('@/views/LDAPSettings.vue'),
        meta: { locale: 'menu.system.ldap', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'remote-wipe',
        name: 'RemoteWipe',
        component: () => import('@/views/RemoteWipe.vue'),
        meta: { locale: 'menu.system.remoteWipe', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'regions',
        name: 'RegionsConfig',
        component: () => import('@/views/RegionsConfig.vue'),
        meta: { locale: 'menu.system.regions', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'data-masking',
        name: 'DataMasking',
        component: () => import('@/views/DataMasking.vue'),
        meta: { locale: 'menu.system.dataMasking', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'audit-logs',
        name: 'AuditLogs',
        component: () => import('@/views/AuditLogs.vue'),
        meta: { locale: 'menu.system.auditLogs', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'i18n',
        name: 'Internationalization',
        component: () => import('@/views/Internationalization.vue'),
        meta: { locale: 'menu.system.i18n', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'edge-nodes',
        name: 'EdgeNodes',
        component: () => import('@/views/EdgeNodes.vue'),
        meta: { locale: 'menu.system.edgeNodes', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'rate-limit',
        name: 'APIRateLimit',
        component: () => import('@/views/APIRateLimit.vue'),
        meta: { locale: 'menu.system.rateLimit', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'certificates',
        name: 'Certificates',
        component: () => import('@/views/Certificates.vue'),
        meta: { locale: 'menu.system.certificates', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'smart-home',
        name: 'SmartHome',
        component: () => import('@/views/SmartHomeDevices.vue'),
        meta: { locale: 'menu.system.smartHome', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'simulation',
        name: 'Simulation',
        component: () => import('@/views/SimulationEnvironment.vue'),
        meta: { locale: 'menu.system.simulation', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'api-explorer',
        name: 'APIExplorer',
        component: () => import('@/views/APIExplorer.vue'),
        meta: { locale: 'menu.system.apiExplorer', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'pressure-test',
        name: 'PressureTesting',
        component: () => import('@/views/PressureTesting.vue'),
        meta: { locale: 'menu.system.pressureTest', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'ble-debug',
        name: 'BLEDebugging',
        component: () => import('@/views/BLEDebugging.vue'),
        meta: { locale: 'menu.system.bleDebug', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'dataset',
        name: 'DatasetManagement',
        component: () => import('@/views/DatasetManagement.vue'),
        meta: { locale: 'menu.system.dataset', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'cicd',
        name: 'CICDIntegration',
        component: () => import('@/views/CICDIntegration.vue'),
        meta: { locale: 'menu.system.cicd', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'compliance',
        name: 'DataCompliance',
        component: () => import('@/views/DataCompliance.vue'),
        meta: { locale: 'menu.system.compliance', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'offline-sync',
        name: 'OfflineSync',
        component: () => import('@/views/OfflineSync.vue'),
        meta: { locale: 'menu.system.offlineSync', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'notification',
        name: 'NotificationCenter',
        component: () => import('@/views/NotificationCenter.vue'),
        meta: { locale: 'menu.system.notification', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'data-export',
        name: 'DataExport',
        component: () => import('@/views/DataExport.vue'),
        meta: { locale: 'menu.system.dataExport', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'customer-service',
        name: 'CustomerService',
        component: () => import('@/views/CustomerService.vue'),
        meta: { locale: 'menu.system.customerService', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'product',
        name: 'ProductManagement',
        component: () => import('@/views/ProductManagement.vue'),
        meta: { locale: 'menu.system.product', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'price-strategy',
        name: 'PriceStrategy',
        component: () => import('@/views/PriceStrategy.vue'),
        meta: { locale: 'menu.system.priceStrategy', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'storage',
        name: 'StorageManagement',
        component: () => import('@/views/StorageManagement.vue'),
        meta: { locale: 'menu.system.storage', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'health',
        name: 'SystemHealth',
        component: () => import('@/views/SystemHealth.vue'),
        meta: { locale: 'menu.system.health', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'settings',
        name: 'SettingsCenter',
        component: () => import('@/views/SettingsCenter.vue'),
        meta: { locale: 'menu.system.settings', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'feedback',
        name: 'FeedbackManagement',
        component: () => import('@/views/FeedbackManagement.vue'),
        meta: { locale: 'menu.system.feedback', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
  {
    path: '/developer',
    name: 'Developer',
    component: DEFAULT_LAYOUT,
    meta: {
      locale: 'menu.developer',
      requiresAuth: true,
      icon: 'icon-code',
      order: 1,
    },
    children: [
      {
        path: 'apps',
        name: 'DevApps',
        component: () => import('@/views/DeveloperPortal.vue'),
        meta: { locale: 'menu.developer.apps', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'logs',
        name: 'DevLogs',
        component: () => import('@/views/APILogs.vue'),
        meta: { locale: 'menu.developer.logs', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'tokens',
        name: 'AccessTokenManagement',
        component: () => import('@/views/AccessTokenManagement.vue'),
        meta: { locale: 'menu.openplatform.tokens', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'webhooks',
        name: 'APIWebhooks',
        component: () => import('@/views/APIWebhooks.vue'),
        meta: { locale: 'menu.openplatform.webhooks', requiresAuth: true, roles: ['*'] },
      },
      {
        path: 'marketplace',
        name: 'AppMarketplace',
        component: () => import('@/views/AppMarketplace.vue'),
        meta: { locale: 'menu.openplatform.marketplace', requiresAuth: true, roles: ['*'] },
      },
    ],
  },
];

export default [DASHBOARD, ...MDM_ROUTES];
