import { createApp } from 'vue';
import ArcoVue from '@arco-design/web-vue';
import ArcoVueIcon from '@arco-design/web-vue/es/icon';
import {
  IconHome,
  IconUser,
  IconSettings,
  IconList,
  IconTable,
  IconDashboard,
  IconTools,
  IconLock,
  Icon公安,
  IconPeople,
  IconTree,
  IconShoppingCart,
  IconPromotion,
  IconGift,
  IconMessage,
  IconCheckCircle,
  IconHistory,
  IconEdit,
  IconDelete,
  IconPlus,
  IconUpload,
  IconDownload,
  IconSearch,
  IconFilter,
  IconRefresh,
  IconClose,
  IconLeft,
  IconRight,
  IconMore,
  IconPen,
  IconAttachment,
  IconCalendar,
  IconCaretRight,
  IconCaretLeft,
  IconCaretUp,
  IconCaretDown,
  IconLink,
  IconFullscreen,
  IconExitFullscreen,
  IconMenu,
  IconInfoCircle,
  IconWarningCircle,
  IconQuestionCircle,
  IconSpinner,
  IconLocation,
  IconPhone,
  IconEmail,
  IconCamera,
  IconTag,
  IconBranch,
  IconExperiment,
  IconAi,
  IconRobot,
  IconActivity,
  IconThunder,
  IconSound,
  IconNotification,
  IconMessageSolid,
  IconSafe,
  IconEnvironment,
  IconCar,
  IconWifi,
  IconBattery,
  IconCpu,
  IconStorage,
  IconEye,
  IconEyeInvisible,
  IconScan,
  IconQrcode,
  IconFocus,
  IconBlock,
  IconFire,
  IconStop,
  IconPlayArrow,
  IconPause,
  IconSkipNext,
  IconSkipPrevious,
  IconArrowUp,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconToTop,
  IconToBottom,
} from '@arco-design/web-vue/es/icon';
import globalComponents from '@/components';
import router from './router';
import store from './store';
import i18n from './locale';
import directive from './directive';
import './mock';
import App from './App.vue';
// Styles are imported via arco-plugin. See config/plugin/arcoStyleImport.ts in the directory for details
// 样式通过 arco-plugin 插件导入。详见目录文件 config/plugin/arcoStyleImport.ts
// https://arco.design/docs/designlab/use-theme-package
import '@/assets/style/global.less';
import '@/api/interceptor';

const app = createApp(App);

app.use(ArcoVue, {});
app.use(ArcoVueIcon, {
  IconHome,
  IconUser,
  IconSettings,
  IconList,
  IconTable,
  IconDashboard,
  IconTools,
  IconLock,
  Icon公安,
  IconPeople,
  IconTree,
  IconShoppingCart,
  IconPromotion,
  IconGift,
  IconMessage,
  IconCheckCircle,
  IconHistory,
  IconEdit,
  IconDelete,
  IconPlus,
  IconUpload,
  IconDownload,
  IconSearch,
  IconFilter,
  IconRefresh,
  IconClose,
  IconLeft,
  IconRight,
  IconMore,
  IconPen,
  IconAttachment,
  IconCalendar,
  IconCaretRight,
  IconCaretLeft,
  IconCaretUp,
  IconCaretDown,
  IconLink,
  IconFullscreen,
  IconExitFullscreen,
  IconMenu,
  IconInfoCircle,
  IconWarningCircle,
  IconQuestionCircle,
  IconSpinner,
  IconLocation,
  IconPhone,
  IconEmail,
  IconCamera,
  IconTag,
  IconBranch,
  IconExperiment,
  IconAi,
  IconRobot,
  IconActivity,
  IconThunder,
  IconSound,
  IconNotification,
  IconMessageSolid,
  IconSafe,
  IconEnvironment,
  IconCar,
  IconWifi,
  IconBattery,
  IconCpu,
  IconStorage,
  IconEye,
  IconEyeInvisible,
  IconScan,
  IconQrcode,
  IconFocus,
  IconBlock,
  IconFire,
  IconStop,
  IconPlayArrow,
  IconPause,
  IconSkipNext,
  IconSkipPrevious,
  IconArrowUp,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconToTop,
  IconToBottom,
});

app.use(router);
app.use(store);
app.use(i18n);
app.use(globalComponents);
app.use(directive);

app.mount('#app');
